[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run src/main.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_BUILD_CMD = "pip install streamlit requests pillow pydeck"